spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:podixo03@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/log-file-ms-avaliador-credito.log