spring:
  application:
    name: eurikaserver
  security:
    user:
      name: cursoms-eureka-user
      password: podixo03

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false