spring:
  application:
    name: mscartoes
  rabbitmq:
    host: rabbitmq # nome do container RabbitMQ
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:podixo03@eureka:8761/eureka # nome do container Eureka
